### ISSUE TITLE
Feature Request: Disable buttons and percentage

### ISSUE THREAD

**Issue by MrBamse** [marcelhoogantink/enhanced-shutter-card#15]
Hi! It's awesome that you picked up the development of this card, thank you!! :)

Would it be possible to add the ability to disable the buttons and the percentage so that one only had the "touch-n-drag" option? 

I believe it would look really nice and neat, especially if you have multiple blinds! :)

Appreciate your consideration!

**Comment by jojoBzh** [comment]
Hello,
I am also very interested in this option for the same reasons.
Additionally, it would be great to have the ability to adjust the size of the title and the percentage.
Thank you for this great work!
Best regards,

**Comment by marcelhoogantink** [comment]
This option is in development.

**Comment by jojoBzh** [comment]
Thank you, that's amazing!
I just experimented with this dashboard, and by mistake, while swiping on a shutter, I accidentally opened it.
It gave me quite a scare because it's a house I control remotely, and the alarm was activated.
Luckily, I managed to close it in time :-)
Would it be possible to have a "passive" mode, meaning one that only shows the status of the shutters, to avoid the risk of opening them by mistake?
Thanks again

**Comment by marcelhoogantink** [comment]
@jojoBzh please create a new Feature Request for 'passive mode' to keep the request clear and single, thank you.

**Comment by jojoBzh** [comment]
I also just noticed that when I close the shutter (directly via the entity cover.shutter_id), once the shutter is closed, the buttons reappear despite this configuration :
type: custom:enhanced-shutter-card
entities:
  - entity: cover.shutter_id
    name: Chambre
    name_disabled: true
    base_height_px: 90
    base_width_px: 90
    opening_position: bottom
    buttons_position: bottom
    always_percentage: false
    passive_mode: true
    button_up_hide_states:
      - opening
      - open
      - closing
      - close
      - partial_open
    button_down_hide_states:
      - opening
      - open
      - closing
      - close
      - partial_open
    button_stop_hide_states:
      - opening
      - open
      - closing
      - close
      - partial_open

**Comment by marcelhoogantink** [comment]
Hi @jojoBzh ,

Please create a new issue when found one, and do not continue in an already solved issue.
In that way i can keep track of the issues and requests the best way.

Thank you!
