### ISSUE TITLE
Option partial_close_percentage not working

### ISSUE THREAD

**Issue by Paul-Vdp** [marcelhoogantink/enhanced-shutter-card#17]
On a couple of covers I set the partial_close_percentage option. The corresponding button did appear, but when activated results in an error message 'Failed to perform the action cover/set_cover_position. required key not provided @ data['position']'.
By the way, this DID work with the old shutter card ...

**Comment by marcelhoogantink** [comment]
Please provide me the configuration for the shutter where this 'partail' option does not work.
Thank you.

**Comment by Paul-Vdp** [comment]
There you go :
``

**Comment by marcelhoogantink** [comment]
Your 'partial' line is not correctly indended. Place the lines two spaces further to the right.

**Comment by Paul-Vdp** [comment]
I did say that github makes a mess of it. This printscreen shows maybe better that everything is as it should be :

![image](https://github.com/user-attachments/assets/f996fbf9-920c-4165-84db-a98a6b8e04c1)

**Comment by marcelhoogantink** [comment]
Found the issue.
I expect to release a new big release at the end of this week.
With new features and problems fixed. This one will also be fixed.

**Comment by Paul-Vdp** [comment]
Ok, thanks ...
