### ISSUE TITLE
Option partial_close_percentage, error "cover/set_cover_position. required key not provided @ data['position']"  V1.1.0b0

### ISSUE THREAD

**Issue by fredfred41** [marcelhoogantink/enhanced-shutter-card#21]
Hi,

I have the same issue as Paul-Vdp, with the partial_close_percentage option.
[https://github.com/marcelhoogantink/enhanced-shutter-card/issues/17](https://github.com/marcelhoogantink/enhanced-shutter-card/issues/17)

I tried using your last beat release V1.1.0b0

The error message is the same:

"cover/set_cover_position. required key not provided @ data['position']"

Here is my yaml:
![image](https://github.com/user-attachments/assets/b970bba2-3ce7-49d8-b229-fe898686b2f4)

I previously used shutter-card everything work great, partial_close_percentage option included, but yours seems better , so I would like to switch to it.

my yaml : 

![image](https://github.com/user-attachments/assets/c9502278-682f-4e81-8afb-563202868450)

I’m not very familiar with GitHub, so I’m not sure if my approach is the right way to do things on GitHub. I apologize for that.

Great job for your card.

**Comment by fredfred41** [comment]
It seems to be working really well. thanks for your time. even the fact that I force download beta version, will I have next stable version downloaded when available?

**Comment by marcelhoogantink** [comment]
Yes!
I close thsi issue
