### ISSUE TITLE
Section's default view is broken

### ISSUE THREAD

**Issue by Sangoku** [marcelhoogantink/enhanced-shutter-card#28]
![image](https://github.com/user-attachments/assets/44e9ce33-f973-4310-b9e7-df7bc539ed96)

This is when you stack them. They dont work with the new style at all. 

The menu is 4 sections and the panel is 1 panel wide. It is also completly broken on the phone view.  

`
type: horizontal-stack
cards:
  - type: custom:enhanced-shutter-card
    entities:
      - entity: cover.rollos_arbeitszimmer
        name: Radna
        title_position: bottom
        blind_color: "#383E42"
        buttons_position: right
        invert_percentage: true
      - entity: cover.rollos_schlafzimmer
        name: Spavaca
        title_position: bottom
        blind_color: "#383E42"
        buttons_position: right
        invert_percentage: true
      - entity: cover.rollos_kinderzimmer
        name: Djecija
        title_position: bottom
        blind_color: "#383E42"
        buttons_position: right
        invert_percentage: true
  - type: custom:enhanced-shutter-card
    entities:
      - entity: cover.rollos_wohnzimmer
        name: Dnevna
        title_position: bottom
        blind_color: "#383E42"
        buttons_position: right
        invert_percentage: true
      - entity: cover.rollos_kuche
        name: Kuhinja
        title_position: bottom
        blind_color: "#383E42"
        buttons_position: right
        invert_percentage: true
      - entity: cover.rollos_kuchentur
        name: Kuh Vrata
        title_position: bottom
        blind_color: "#383E42"
        buttons_position: right
        invert_percentage: true

`

The one above which gets overwriten is 

`type: custom:enhanced-shutter-card
entities:
  - entity: cover.rollos_arbeitszimmer
    name: My Enhanced Shuttter
`

Even the editor is broken

![image](https://github.com/user-attachments/assets/90d2aa64-02c4-48d0-ac9e-69e0fd02eb36)

**Comment by marcelhoogantink** [comment]
Hi @Sangoku ,

Sorry that is does not work for you.

Whitch version do you use?
What do you mean with 'the new style'? Do you use Sections?
Can you supply the yaml of the whole dashboard?
Then I can look into it better.

The editor is not broken, at the moment there is not a UI-editor for the card. I am working on it.
Also 'blind-color'is not an option in this card.

You may change the sie of the images to fit the card.

**Comment by marcelhoogantink** [comment]
Meanwhile, I am working on an improvement.

**Comment by Sangoku** [comment]
Latest version of your card. 
Newest home asistant. 
Newest version Chrome on Mack OS

![image](https://github.com/user-attachments/assets/56b95435-6f3c-42de-aee7-4ba1763c935d)
![image](https://github.com/user-attachments/assets/3e688591-00be-4b14-9b4e-9563afff0dea)
![image](https://github.com/user-attachments/assets/bc3ddd31-6d76-4711-96c8-bf76fc4a7625)
![image](https://github.com/user-attachments/assets/e492c2bf-6aa0-4eaa-9fd3-caacc718d34d)

Even with all settings removed, same behaviour
`type: horizontal-stack
cards:
  - type: custom:enhanced-shutter-card
    entities:
      - entity: cover.rollos_arbeitszimmer
        name: Radna 
        invert_percentage: true
      - entity: cover.rollos_schlafzimmer
        name: Spavaca 
        invert_percentage: true
      - entity: cover.rollos_kinderzimmer
        name: Djecija 
        invert_percentage: true
  - type: custom:enhanced-shutter-card
    entities:
      - entity: cover.rollos_wohnzimmer
        name: Dnevna 
        invert_percentage: true
      - entity: cover.rollos_kuche
        name: Kuhinja 
        invert_percentage: true
      - entity: cover.rollos_kuchentur
        name: Kuh Vrata 
        invert_percentage: true
`
I also have the standard blinds installed.. maybe that helps. 

It looks same on the phone to.

Does it work on your setup? if yes i will debug, maybe some otther addon breaking things on my end.

**Comment by marcelhoogantink** [comment]
Hi @Sangoku ,

Thank you for your extra info.
In the future, please do not use 'latest version', write the real versions please. For now it is OK.

Regarding the overflow of the card, its on my side. Calculation of the needed size of the card for the new Sections view, is hard, due to missing detailed info of the grid in Home Assistant. I worked it out, and I will release a new version (v1.1.1) later today.

I like you to check this new version and let me know it works better in this new version

**Comment by marcelhoogantink** [comment]
Solved in v1.1.1

**Comment by Sangoku** [comment]
Nope Stil present. 
![image](https://github.com/user-attachments/assets/c3885e72-9448-4907-9751-2096e92f645e)
v1.1.1 redownloaded. 
Version 131.0.6778.205 (Official Build) (arm64)

![image](https://github.com/user-attachments/assets/c7fbeba7-54d7-4f75-8728-d3a964af2317)


It looks ok in the editor now :) 

![image](https://github.com/user-attachments/assets/aba814f7-910e-41d3-9879-c7fb079a5a81)

But still same behavior in the grid sadly..

**Comment by marcelhoogantink** [comment]
Ok, what do you expect?
Automatic resize of the image?
That is not implemented at this moment. 
Now you should resize the image with base_width_px setting.

**Comment by Sangoku** [comment]
Works! NOICE WORK!
