### ISSUE TITLE
New version does not render Well with horizontal-stack

### ISSUE THREAD

**Issue by mochoandre** [marcelhoogantink/enhanced-shutter-card#30]
Hello,
I Have 4 windows side by side and I use horizontal-stack to displace them with enhaced-shuter-card (before shuter-card).
As there is a lack of space to show all the windows and controls, before all the controls were shown and like half of the windows picture.

I have upated enhaced-shuter-card and home assistant and now it is rending all windows picture full size outside of the horizontal stack like this

![Captura de ecrã 2024-12-22 000043](https://github.com/user-attachments/assets/0f1b216e-bbf6-44df-a62a-3daef60e826c)

Thank you
Best Regards

**Comment by marcelhoogantink** [comment]
I am working on an improvement.

**Comment by marcelhoogantink** [comment]
Solved in v1.1.1

**Comment by mochoandre** [comment]
For me still renders the same way, Firefox, Chrome and HA app.

But anyway, many thanks for looking in to it.
Best regards and happy hollydays
