### ISSUE TITLE
Disable Images

### ISSUE THREAD

**Issue by Veldkornet** [marcelhoogantink/enhanced-shutter-card#32]
How can I disable the images and just make it look (and work, where you can drag the shutter position) like the original shutter card?

![image](https://github.com/user-attachments/assets/cb746b4a-692c-44f0-b71b-579de50d46a3)

All of these fake images just makes my dashboard look silly.

**Comment by marcelhoogantink** [comment]
Dragging is/should be possible. 
To disable the image, use the view_image setting and define a color in stead of an image. See the readme.

**Comment by xeijin** [comment]
Specifically, you want to add something like **view_image: "#fff0"** to make sure the background is transparent - this will ensure it displays correctly regardless of light/dark theme, or if you have a custom background image for the dashboard.
