### ISSUE TITLE
add custom text to display state 

### ISSUE THREAD

**Issue by jluc2808** [marcelhoogantink/enhanced-shutter-card#33]
bonjour, 

a cause de quelques état incompréhensible 

j'avais créé un fork de l'original shutter-card mais très limité à l'ajout de la possibilité de mettre un texte "custom" aux états  des equipements 
- text_open 
- text_close
- text_no_position 
et un binaire pour afficher ou non le texte de  text_no_position 

pourriez-vous reprendre cela dans votre enhanced-shutter-card ? 

merci

**Comment by marcelhoogantink** [comment]
I will look into it.

**Comment by marcelhoogantink** [comment]
The translations are changed already. Is it still neede for you and why?

**Comment by jluc2808** [comment]
i havn't saw this modification, so no need to change anything it's perfect .

**Comment by jluc2808** [comment]
just a thing because it's perhaps inside 
when i set the 
    base_height_px: 50
    base_width_px: 50
the window image is rebuit according with the new height and width 
but the button (up,stop,down) are still with the same height/width (depending of the position)

could you add the resizing of the button according with the size iamge of the shutter/windows ?

**Comment by marcelhoogantink** [comment]
I created a new issue for this question. Close this issue now.
